spring.application.name=dinso-finbanken
spring.datasource.url=jdbc:h2:mem:finbanken;DB_CLOSE_DELAY=-1
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
dinso.security.jwt-secret=dinso-finbanken-local-demo-signing-key
dinso.customer.portals=PRIVATE
dinso.customer.locales=en
dinso.customer.default-locale=en
dinso.customer.maximum-funds=10
dinso.customer.maximum-leave-months=0
dinso.customer.leave-reasons=
dinso.customer.show-fees=false
dinso.customer.show-transactions=true
dinso.customer.show-traditional-bonus-rate=false
dinso.customer.company-mutations=
